name: Lint and test
on:
  push:
    paths:
      - '**.el'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: ["snapshot"]
    steps:
    - uses: cachix/install-nix-action@v18
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cat <(jq -r '.nodes.root.inputs | map(.) | .[]' .nomake/flake.lock) \
            <(jq -r 'keys | .[]' .nomake/archive.lock) \
            <(echo 'package-lint') \
            | xargs emacs -batch -l package --eval \
            "(progn
                (push '(\"melpa\" . \"https://melpa.org/packages/\")
                      package-archives)
                (package-initialize)
                (when command-line-args-left
                  (package-refresh-contents))
                (dolist (package-name command-line-args-left)
                  (let ((package (intern package-name)))
                     (when (and package
                                (not (memq package
                                           '(xmind-org))))
                       (package-install (cadr (assq package 
                                                    package-archive-contents)))))))"
    - name: Byte-compile
      if: ${{ false }}
      run: |
        emacs -batch -l bytecomp -l package --eval "(push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives)" --eval "(package-initialize)" -L . \
          --eval "(setq byte-compile-error-on-warn t)" \
          -f batch-byte-compile 'xmind-org.el'
    - run: |
        emacs -l package --eval "(push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives)" --eval "(package-initialize)" -L . -batch -l package-lint \
          --eval "(setq package-lint-main-file \"xmind-org.el\")" \
          -f package-lint-batch-and-exit 'xmind-org.el'
      name: Run package-lint

    - name: Download test data
      run: |
        curl -OL https://github.com/ivan-kleshnin/frontend-mindmaps/raw/master/middle.xmind
    - run: nix run .#test
